<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="" lang="">
<head>
  <title>Test Results Report - ApiTest</title>
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
  <meta name="description" content="TestNG unit test results." />
  <link href="reportng.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="reportng.js"></script>
</head>
<body>
<h1>ApiTest</h1>
<p>
  Test duration: 16.199s
</p>



  <table class="resultsTable">
    <tr><th colspan="3" class="header failed">Failed Tests</th></tr>
          <tr>
        <td colspan="3" class="group">automationFramework.NextWave2RestApi.ApiCustomerPost</td>
      </tr>
            
<tr>
  <td class="method">
                  apiErrorAddressId
      </td>
  <td class="duration">
    1.569s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-0', 'block')" title="Click to expand/collapse"><b>java.lang.NullPointerException</b></a><br />
    <div class="stackTrace" id="exception-0">
              automationFramework.NextWave2RestApi.ApiCustomerPost.checkError(ApiCustomerPost.java:1019)<br />
              automationFramework.NextWave2RestApi.ApiCustomerPost.apiErrorAddressId(ApiCustomerPost.java:297)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorBlankPhoneNumber
      </td>
  <td class="duration">
    0.036s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-1', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [contact.phone[0].phoneNumber] but found [contact.phone[0].number]</b></a><br />
    <div class="stackTrace" id="exception-1">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              automationFramework.NextWave2RestApi.ApiCustomerPost.checkError(ApiCustomerPost.java:1019)<br />
              automationFramework.NextWave2RestApi.ApiCustomerPost.apiErrorBlankPhoneNumber(ApiCustomerPost.java:420)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorBlankPhoneNumber2
      </td>
  <td class="duration">
    0.054s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-2', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [contact.phone[1].phoneNumber] but found [contact.phone[1].number]</b></a><br />
    <div class="stackTrace" id="exception-2">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              automationFramework.NextWave2RestApi.ApiCustomerPost.checkError(ApiCustomerPost.java:1019)<br />
              automationFramework.NextWave2RestApi.ApiCustomerPost.apiErrorBlankPhoneNumber2(ApiCustomerPost.java:460)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorBlankPhoneNumber3
      </td>
  <td class="duration">
    0.094s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-3', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [contact.phone[2].phoneNumber] but found [contact.phone[2].number]</b></a><br />
    <div class="stackTrace" id="exception-3">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              automationFramework.NextWave2RestApi.ApiCustomerPost.checkError(ApiCustomerPost.java:1019)<br />
              automationFramework.NextWave2RestApi.ApiCustomerPost.apiErrorBlankPhoneNumber3(ApiCustomerPost.java:500)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorBlankPhoneType
      </td>
  <td class="duration">
    0.038s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-4', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [contact.phone[0].phoneType] but found [contact.phone[0].type]</b></a><br />
    <div class="stackTrace" id="exception-4">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              automationFramework.NextWave2RestApi.ApiCustomerPost.checkError(ApiCustomerPost.java:1019)<br />
              automationFramework.NextWave2RestApi.ApiCustomerPost.apiErrorBlankPhoneType(ApiCustomerPost.java:440)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorBlankPhoneType2
      </td>
  <td class="duration">
    0.070s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-5', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [contact.phone[1].phoneType] but found [contact.phone[1].type]</b></a><br />
    <div class="stackTrace" id="exception-5">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              automationFramework.NextWave2RestApi.ApiCustomerPost.checkError(ApiCustomerPost.java:1019)<br />
              automationFramework.NextWave2RestApi.ApiCustomerPost.apiErrorBlankPhoneType2(ApiCustomerPost.java:481)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorBlankPhoneType3
      </td>
  <td class="duration">
    0.057s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-6', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [contact.phone[2].phoneType] but found [contact.phone[2].type]</b></a><br />
    <div class="stackTrace" id="exception-6">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              automationFramework.NextWave2RestApi.ApiCustomerPost.checkError(ApiCustomerPost.java:1019)<br />
              automationFramework.NextWave2RestApi.ApiCustomerPost.apiErrorBlankPhoneType3(ApiCustomerPost.java:521)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorContainConsecutiveCharacterPin
      </td>
  <td class="duration">
    0.085s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-7', 'block')" title="Click to expand/collapse"><b>java.lang.NullPointerException</b></a><br />
    <div class="stackTrace" id="exception-7">
              automationFramework.NextWave2RestApi.ApiCustomerPost.checkError(ApiCustomerPost.java:1019)<br />
              automationFramework.NextWave2RestApi.ApiCustomerPost.apiErrorContainConsecutiveCharacterPin(ApiCustomerPost.java:794)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorContainContigousCharacterPin
      </td>
  <td class="duration">
    0.071s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-8', 'block')" title="Click to expand/collapse"><b>java.lang.NullPointerException</b></a><br />
    <div class="stackTrace" id="exception-8">
              automationFramework.NextWave2RestApi.ApiCustomerPost.checkError(ApiCustomerPost.java:1019)<br />
              automationFramework.NextWave2RestApi.ApiCustomerPost.apiErrorContainContigousCharacterPin(ApiCustomerPost.java:804)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorContainDictionaryPassword
      </td>
  <td class="duration">
    0.070s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-9', 'block')" title="Click to expand/collapse"><b>java.lang.NullPointerException</b></a><br />
    <div class="stackTrace" id="exception-9">
              automationFramework.NextWave2RestApi.ApiCustomerPost.checkError(ApiCustomerPost.java:1019)<br />
              automationFramework.NextWave2RestApi.ApiCustomerPost.apiErrorContainDictionaryPassword(ApiCustomerPost.java:773)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorContainDigitsPassword
      </td>
  <td class="duration">
    0.076s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-10', 'block')" title="Click to expand/collapse"><b>java.lang.NullPointerException</b></a><br />
    <div class="stackTrace" id="exception-10">
              automationFramework.NextWave2RestApi.ApiCustomerPost.checkError(ApiCustomerPost.java:1019)<br />
              automationFramework.NextWave2RestApi.ApiCustomerPost.apiErrorContainDigitsPassword(ApiCustomerPost.java:733)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorContainSpecialCharactersPassword
      </td>
  <td class="duration">
    0.073s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-11', 'block')" title="Click to expand/collapse"><b>java.lang.NullPointerException</b></a><br />
    <div class="stackTrace" id="exception-11">
              automationFramework.NextWave2RestApi.ApiCustomerPost.checkError(ApiCustomerPost.java:1019)<br />
              automationFramework.NextWave2RestApi.ApiCustomerPost.apiErrorContainSpecialCharactersPassword(ApiCustomerPost.java:763)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorInvalidPhoneNumber
      </td>
  <td class="duration">
    0.026s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-12', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [contact.phone[0].phoneNumber] but found [contact.phone[0].number]</b></a><br />
    <div class="stackTrace" id="exception-12">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              automationFramework.NextWave2RestApi.ApiCustomerPost.checkError(ApiCustomerPost.java:1019)<br />
              automationFramework.NextWave2RestApi.ApiCustomerPost.apiErrorInvalidPhoneNumber(ApiCustomerPost.java:430)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorInvalidPhoneNumber2
      </td>
  <td class="duration">
    0.071s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-13', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [contact.phone[1].phoneNumber] but found [contact.phone[1].number]</b></a><br />
    <div class="stackTrace" id="exception-13">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              automationFramework.NextWave2RestApi.ApiCustomerPost.checkError(ApiCustomerPost.java:1019)<br />
              automationFramework.NextWave2RestApi.ApiCustomerPost.apiErrorInvalidPhoneNumber2(ApiCustomerPost.java:470)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorInvalidPhoneNumber3
      </td>
  <td class="duration">
    0.025s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-14', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [contact.phone[2].phoneNumber] but found [contact.phone[2].number]</b></a><br />
    <div class="stackTrace" id="exception-14">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              automationFramework.NextWave2RestApi.ApiCustomerPost.checkError(ApiCustomerPost.java:1019)<br />
              automationFramework.NextWave2RestApi.ApiCustomerPost.apiErrorInvalidPhoneNumber3(ApiCustomerPost.java:510)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorInvalidPhoneType
      </td>
  <td class="duration">
    0.037s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-15', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [contact.phone[0].phoneType] but found [contact.phone[0].type]</b></a><br />
    <div class="stackTrace" id="exception-15">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              automationFramework.NextWave2RestApi.ApiCustomerPost.checkError(ApiCustomerPost.java:1019)<br />
              automationFramework.NextWave2RestApi.ApiCustomerPost.apiErrorInvalidPhoneType(ApiCustomerPost.java:450)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorInvalidPhoneType2
      </td>
  <td class="duration">
    0.046s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-16', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [contact.phone[1].phoneType] but found [contact.phone[1].type]</b></a><br />
    <div class="stackTrace" id="exception-16">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              automationFramework.NextWave2RestApi.ApiCustomerPost.checkError(ApiCustomerPost.java:1019)<br />
              automationFramework.NextWave2RestApi.ApiCustomerPost.apiErrorInvalidPhoneType2(ApiCustomerPost.java:491)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorInvalidPhoneType3
      </td>
  <td class="duration">
    0.081s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-17', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [contact.phone[2].phoneType] but found [contact.phone[2].type]</b></a><br />
    <div class="stackTrace" id="exception-17">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              automationFramework.NextWave2RestApi.ApiCustomerPost.checkError(ApiCustomerPost.java:1019)<br />
              automationFramework.NextWave2RestApi.ApiCustomerPost.apiErrorInvalidPhoneType3(ApiCustomerPost.java:532)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorMaxLengthPassword
      </td>
  <td class="duration">
    0.063s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-18', 'block')" title="Click to expand/collapse"><b>java.lang.NullPointerException</b></a><br />
    <div class="stackTrace" id="exception-18">
              automationFramework.NextWave2RestApi.ApiCustomerPost.checkError(ApiCustomerPost.java:1019)<br />
              automationFramework.NextWave2RestApi.ApiCustomerPost.apiErrorMaxLengthPassword(ApiCustomerPost.java:723)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorMixCasesPassword
      </td>
  <td class="duration">
    0.070s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-19', 'block')" title="Click to expand/collapse"><b>java.lang.NullPointerException</b></a><br />
    <div class="stackTrace" id="exception-19">
              automationFramework.NextWave2RestApi.ApiCustomerPost.checkError(ApiCustomerPost.java:1019)<br />
              automationFramework.NextWave2RestApi.ApiCustomerPost.apiErrorMixCasesPassword(ApiCustomerPost.java:743)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
      </table>


  <table class="resultsTable">
    <tr><th colspan="3" class="header passed">Passed Tests</th></tr>
          <tr>
        <td colspan="3" class="group">automationFramework.NextWave2RestApi.ApiCustomerPost</td>
      </tr>
            
<tr>
  <td class="method">
                  apiErrorBlankAddress
      </td>
  <td class="duration">
    1.073s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorBlankCity
      </td>
  <td class="duration">
    0.064s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorBlankContact
      </td>
  <td class="duration">
    0.056s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorBlankContactFirstName
      </td>
  <td class="duration">
    0.060s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorBlankContactLastName
      </td>
  <td class="duration">
    0.052s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorBlankContactName
      </td>
  <td class="duration">
    0.333s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorBlankContactType
      </td>
  <td class="duration">
    0.064s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorBlankCountry
      </td>
  <td class="duration">
    0.044s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorBlankCustomerType
      </td>
  <td class="duration">
    0.038s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorBlankEmail
      </td>
  <td class="duration">
    0.095s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorBlankPassword
      </td>
  <td class="duration">
    0.044s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorBlankPersonalId
      </td>
  <td class="duration">
    0.077s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorBlankPersonalIdType
      </td>
  <td class="duration">
    0.054s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorBlankPostalCode
      </td>
  <td class="duration">
    0.035s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorBlankState
      </td>
  <td class="duration">
    0.079s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorBlankUserName
      </td>
  <td class="duration">
    0.041s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorContainConsecutiveCharacterPassword
      </td>
  <td class="duration">
    1.250s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorContainUsernamePassword
      </td>
  <td class="duration">
    0.035s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorContainUsernamePin
      </td>
  <td class="duration">
    0.042s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorDuplicateUserName
      </td>
  <td class="duration">
    0.134s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorInvalidContactType
      </td>
  <td class="duration">
    0.055s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorInvalidCountry
      </td>
  <td class="duration">
    0.030s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorInvalidCustomerType
      </td>
  <td class="duration">
    0.036s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorInvalidFormatEmail
      </td>
  <td class="duration">
    0.043s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorInvalidPersonalIdType
      </td>
  <td class="duration">
    0.039s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorInvalidPostalCode
      </td>
  <td class="duration">
    0.066s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorInvalidState
      </td>
  <td class="duration">
    0.032s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorInvalidSuffixId
      </td>
  <td class="duration">
    0.038s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorInvalidUserName
      </td>
  <td class="duration">
    0.116s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorMaxLengthAddress
      </td>
  <td class="duration">
    0.031s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorMaxLengthAddress2
      </td>
  <td class="duration">
    0.052s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorMaxLengthCity
      </td>
  <td class="duration">
    0.047s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorMaxLengthContactFirstName
      </td>
  <td class="duration">
    0.037s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorMaxLengthContactLastName
      </td>
  <td class="duration">
    0.031s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorMaxLengthContactMiddleName
      </td>
  <td class="duration">
    0.034s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorMaxLengthPersonalId
      </td>
  <td class="duration">
    0.033s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorMaxLengthUserName
      </td>
  <td class="duration">
    0.103s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorMaximumLengthEmail
      </td>
  <td class="duration">
    0.040s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorMinLengthPassword
      </td>
  <td class="duration">
    0.042s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorMustContainLettersPassword
      </td>
  <td class="duration">
    0.055s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorNonNumericPin
      </td>
  <td class="duration">
    0.060s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorSecurityAnswerBlank
      </td>
  <td class="duration">
    0.033s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorSecurityAnswerMaxLength
      </td>
  <td class="duration">
    1.268s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorSecurityQuestionBlank
      </td>
  <td class="duration">
    0.044s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorSecurityQuestionInvalid
      </td>
  <td class="duration">
    0.042s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorSpecialCharactersEmail
      </td>
  <td class="duration">
    0.031s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorSpecialCharactersUserName
      </td>
  <td class="duration">
    0.027s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorTooLongPin
      </td>
  <td class="duration">
    0.048s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorTooSmallPin
      </td>
  <td class="duration">
    0.042s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiGetCustomerInfo
      </td>
  <td class="duration">
    0.240s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiGetSuccess
      </td>
  <td class="duration">
    0.028s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiPostSuccess
      </td>
  <td class="duration">
    0.069s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
      </table>
  
</body>
</html>
